library(DMwR2)
library(ISLR)
set.seed(2)
train<-sample(nrow(Default),nrow(Default)/2,replace = FALSE)
ratio<-length(which(Default[train,]$default=="No"))/length(which(Default[train,]$default=="Yes"))
dosmote<-SMOTE(default~.-student,data=Default[train,],perc.over=ratio*100,perc.under=100)
doros<-ROS(default~.-student,data=Default[train,])
length(which(dosmote$default=='No'))
length(which(dosmote$default=='Yes'))